### ISSUE TITLE
Respostas a artigos são mostradas truncadas

### ISSUE THREAD

**Issue by villares** [EncontrosDigitais/bootcamp#1]
Como reproduzir/verificar:
- exemplo de resposta a artigo truncada: https://www.encontrosdigitais.com.br/articles/villares-processing-arduino-velhos-amigos/

**Comment by Vamoss** [comment]
Acho que tem campos demais no formulário também.

Partindo da premissa que apenas usuários logados podem comentar, os outros campos me parecem repetitivos.
![image](https://user-images.githubusercontent.com/245841/77925053-c979ca00-727a-11ea-9405-5bf0ccf06a8b.png)
