### ISSUE TITLE
Traduzir Readme e explicar como rodar o projeto localmente

### ISSUE THREAD

**Issue by Vamoss** [EncontrosDigitais/bootcamp#4]
Colocar em português e explicar como colaborar e como rodar o projeto localmente.

**Comment by Vamoss** [comment]
Enquanto isso não é feito, aqui tem o link de como rodar o projeto localmente:
https://github.com/EncontrosDigitais/bootcamp/wiki/Instalando-e-executando-o-Bootcamp

**Comment by villares** [comment]
Eu acho meio desnecessário traduzir esse Readme tal como está, proponho ir documentando o que o projeto realmente tá fazendo...

Fiz uma proposta https://github.com/EncontrosDigitais/bootcamp/pull/7
