### ISSUE TITLE
sugestão de melhoria: link para este repositório ou para issues no site

### ISSUE THREAD

**Issue by villares** [EncontrosDigitais/bootcamp#6]
Acho que vai ajudar na comunicação das questões :)

**Comment by Vamoss** [comment]
Onde você sugere colocar?

Pensei em criar uma página "Sobre", e lá colocar tudo a respeito do projeto.

**Comment by villares** [comment]
Uma página sobre seria ótimo! Tá faltando mesmo. Será um bom lugar.

E quais os seus planos para a página de rosto do site? Destaques/ conteúdos recentes?

**Comment by Vamoss** [comment]
Na home andei pensando sobre uma arte construída por membros da comunidade.
Cada mês a gente poderia ir trocando.
Abri uma issue específica:
https://github.com/EncontrosDigitais/bootcamp/issues/19

**Comment by Vamoss** [comment]
Oi @villares fiz uma página de sobre para o site:
https://encontrosdigitais.com.br/sobre/

A motivação foi o PCD que começa amanhã e estava preocupado das pessoas entenderem melhor como colaborar.

Obg pela sugestão! Vou fechar, mas fique a vontade em reabrir se tiver algum comentário sobre a página.
